Implement _mm_hsub_ps
DLTcollab/sse2neon pull request #112
Opened 2020-08-25 08:06 UTC by HowJMay

2020-08-25 09:26 UTC, jserv commented on sse2neon.h
> +
Keep single line separation.

2020-08-25 09:31 UTC, jserv commented on sse2neon.h
> +    float32x4x2_t rev_vec = vuzpq_f32(_a, _b);
You can provide A64 shortcut as following:
```c
    return vsubq_f32(vuzp1q_f32(_a, _b), vuzp2q_f32(_a,  _b));
```

Check [Neon Intrinsics Reference](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics) for details.

2020-08-25 09:35 UTC, jserv requested changes
Ensure A64 path is implemented.

2020-08-25 09:38 UTC, jserv commented on sse2neon.h
> +    return vsubq_f32(vuzp1q_f32(_a, _b), vuzp2q_f32(_a, _b));
Move A64-specific implementation in the top-half of function body.

2020-08-25 13:52 UTC, jserv approved these changes

2020-08-26 03:23 UTC, marktwtn requested changes

2020-08-26 03:23 UTC, marktwtn commented on tests/impl.h
> +    TYPE(mm_hsub_ps)                  \
The class is `SSE3`.

2020-08-26 03:23 UTC, marktwtn commented on sse2neon.h
> +    return vsubq_f32(vuzp1q_f32(_a, _b), vuzp2q_f32(_a, _b));
Add `vreinterpretq_m128_f32` and `vreinterpretq_f32_m128`.

2020-08-26 03:23 UTC, marktwtn commented on sse2neon.h
> +    float32x4x2_t rev_vec = vuzpq_f32(_a, _b);
Add `vreinterpretq_f32_m128`.

2020-08-26 06:36 UTC, marktwtn approved these changes

2020-08-26 10:16 UTC, merged