feat: Implement instrinsics _mm_store_pd1
DLTcollab/sse2neon pull request #250
Opened 2020-12-29 17:01 UTC by HowJMay

2020-12-29 17:35 UTC, jserv commented on sse2neon.h
> +
You can add macro:
```c
#define _mm_store1_pd _mm_store_pd1
```

The two intrinsics are functionally the same.

2020-12-30 03:22 UTC, marktwtn requested changes

2021-01-01 12:31 UTC, marktwtn requested changes

2021-01-01 12:31 UTC, marktwtn commented on tests/impl.h
> +    TYPE(mm_store_pd1)                \
Please add `mm_store1_pd` as well.

2021-01-02 09:03 UTC, marktwtn approved these changes

2021-01-02 10:52 UTC, merged