refactor: Change mm_blendv_ps to integer operation
DLTcollab/sse2neon pull request #256
Opened 2021-01-02 08:18 UTC by HowJMay

Mapping `_mm_blendv_ps` intrinsics with `vbslq_f32` would cause lower
accuracy. We can take some integer oprations then call `vbslq_f32`. In
this way, the accuracy would enhance to the way that we take pure
integer steps.

2021-01-02 21:59 UTC, marktwtn requested changes
Please rewrite the commit message. It is quite confusing.
I do not see anything that related to the accuracy.
I believe that the original implementation is wrong, so you might need to change the `refactor` to `fix`.

What would happen if you run the tests with the original implementation?

2021-01-02 21:59 UTC, marktwtn commented on tests/impl.cpp
> +                           impl.mTestFloats[2], impl.mTestFloats[3]};
Replace with `i`, `i+1`, `i+2`, `i+3`.

2021-01-02 21:59 UTC, marktwtn commented on tests/impl.cpp
> +    __m128 mask = _mm_load_ps(_mask);
Replace with `do_mm_load_ps`.

2021-01-03 06:25 UTC, HowJMay commented
> Please rewrite the commit message. It is quite confusing.
> I do not see anything that related to the accuracy.
> I believe that the original implementation is wrong, so you might need to change the `refactor` to `fix`.
> 
> What would happen if you run the tests with the original implementation?

In the original implementation, the last a few digits are wrong, so I thought the problem that the original implementation has is relating to accuracy. But, yeah, I should change the git commit message to fix instead of refactor

2021-01-03 20:33 UTC, jserv commented
> In the original implementation, the last a few digits are wrong, so I thought the problem that the original implementation has is relating to accuracy. But, yeah, I should change the git commit message to fix instead of refactor

Change the subject of this pull request accordingly.

2021-01-06 01:55 UTC, marktwtn commented
The request changes are not handled.

2021-01-06 02:05 UTC, jserv approved these changes
The subject is misleading. Revise it.

2021-01-08 16:09 UTC, marktwtn approved these changes

2021-01-08 16:13 UTC, merged