feat: Implement intrinsics _mm_insert_pi16
DLTcollab/sse2neon pull request #258
Opened 2021-01-02 09:52 UTC by HowJMay

2021-01-02 10:54 UTC, jserv approved these changes

2021-01-02 21:18 UTC, marktwtn requested changes

2021-01-02 21:18 UTC, marktwtn commented on sse2neon.h
> +#define _mm_insert_pi16(a, b, imm)                               \
Please add the comment of the instrinsic description and link.

2021-01-02 21:18 UTC, marktwtn commented on tests/impl.h
> +    TYPE(mm_insert_pi16)              \
The instruction is `SSE` not `SSE2`.

2021-01-02 21:18 UTC, marktwtn commented on tests/impl.cpp
> +    const int16_t insert = (int16_t) impl.mTestInts[0];
Replace `0` with `i` or `i+4`.

2021-01-03 12:20 UTC, marktwtn approved these changes

2021-01-03 20:35 UTC, merged