Add intrinsics _mm_sub_pd
DLTcollab/sse2neon pull request #265
Opened 2021-01-06 19:16 UTC by JishinMaster

2021-01-07 05:20 UTC, marktwtn requested changes
Please rebase the commits to a single one.

2021-01-07 05:20 UTC, marktwtn commented on sse2neon.h
> +// https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=sub_pd
Replace with
```
// Subtract packed double-precision (64-bit) floating-point elements in b from packed double-precision (64-bit) floating-point elements in a, and store the results in dst.
// 
//   FOR j := 0 to 1
//     i := j*64
//     dst[i+63:i] := a[i+63:i] - b[i+63:i]
//   ENDFOR
//  https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=mm_sub_pd

```

2021-01-07 05:20 UTC, marktwtn commented on tests/impl.h
> +    TYPE(mm_sub_pd)                   \
The intrinsic type is `SSE2`.
Please place it in the correct classification.

2021-01-07 05:20 UTC, marktwtn commented on tests/impl.h
> +    TYPE(mm_sub_pd)                   \
Reference: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE2

2021-01-07 05:20 UTC, marktwtn commented on tests/impl.cpp
> +result_t test_mm_sub_pd(const SSE2NEONTestImpl &impl, uint32_t i)
Place it in the correct classification.

2021-01-11 01:19 UTC, marktwtn approved these changes

2021-01-11 01:44 UTC, merged

2021-01-11 01:44 UTC, jserv commented
Thank @JishinMaster for contributing!