Add intrinsics _mm_div_pd
DLTcollab/sse2neon pull request #266
Opened 2021-01-06 19:25 UTC by JishinMaster

2021-01-08 10:39 UTC, jserv requested changes
Please rebase the latest "master" branch.

2021-01-08 13:55 UTC, JishinMaster commented
What is the proper way to rebase to the master?
Since the FMA pull request is still pending, I updated my master branch with a git merge before creating this feature branch.
Hence the work in progress commits which appear but are not directly related.
I am no git expert :(

2021-01-10 02:45 UTC, marktwtn commented
> What is the proper way to rebase to the master?
> Since the FMA pull request is still pending, I updated my master branch with a git merge before creating this feature branch.
> Hence the work in progress commits which appear but are not directly related.
> I am no git expert :(

- Get the newest master/main branch
- Checkout to the branch you are working with
- `$ git rebase master`
-  Fix conflict and make sure the git rebase success
-  `$ git rebase -i master` and make the multiple commits into single one, the make sure the git rebase success

2021-01-10 16:27 UTC, marktwtn requested changes

2021-01-10 16:27 UTC, marktwtn commented on sse2neon.h
> +// https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_div_pd
Please use the description and operation of [_mm_div_pd](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_div_pd)

2021-01-11 01:19 UTC, marktwtn approved these changes

2021-01-11 01:19 UTC, marktwtn approved these changes

2021-01-11 01:43 UTC, merged

2021-01-11 01:43 UTC, jserv commented
Thank @JishinMaster for contributing!