refactor: Arrange impl.cpp in the as impl.h
DLTcollab/sse2neon pull request #269
Opened 2021-01-12 15:32 UTC by HowJMay

Rearrange the tests in impl.cpp as the same order in impl.h.

Tests start to report intrinsics coverage rate from this commit.

2021-01-13 00:29 UTC, marktwtn requested changes
The subject of the git commit message is weird.
Please rewrite the sentence `Arrange impl.cpp in the as impl.h`.

2021-01-13 00:29 UTC, marktwtn commented on tests/main.cpp
> +        (float) (passCount + failedCount) /
I think we should not include `failedCount` here.

2021-01-13 12:43 UTC, jserv requested changes
Rewrite the subject. You should address the motivation and purpose of this change.

2021-01-13 13:20 UTC, HowJMay commented
> Rewrite the subject. You should address the motivation and purpose of this change.

I have separated the coverage report to another PR

2021-01-14 02:07 UTC, marktwtn commented
Rewrite the subject `Arrange impl.cpp in the as impl.h` before you requested my review.

2021-01-14 02:56 UTC, HowJMay commented
> Rewrite the subject `Arrange impl.cpp in the as impl.h` before you requested my review.
> The `in the as` makes no sense.

done

2021-01-14 02:58 UTC, marktwtn commented
> > Rewrite the subject `Arrange impl.cpp in the as impl.h` before you requested my review.
> > The `in the as` makes no sense.
> 
> done

The commit itself is not handled.

2021-01-18 03:43 UTC, marktwtn approved these changes

2021-01-24 13:12 UTC, merged