feat: Implement intrinsics _mm_sub_sd
DLTcollab/sse2neon pull request #272
Opened 2021-01-13 14:26 UTC by HowJMay

2021-01-14 02:48 UTC, marktwtn commented on tests/impl.cpp
> +    return validateDouble(c, *(double *) &d0, *(double *) &d1);
Please rebase to the newest main branch to avoid fixing code convention from the previous commit.

2021-01-15 01:32 UTC, marktwtn approved these changes

2021-01-15 05:49 UTC, jserv requested changes
Fix the conflicts

2021-01-16 02:36 UTC, marktwtn approved these changes

2021-01-16 03:24 UTC, merged