test: Cover more input values of _mm_extract_*
DLTcollab/sse2neon pull request #397
Opened 2021-05-03 18:18 UTC by HowJMay

2021-05-04 02:47 UTC, marktwtn requested changes

2021-05-04 02:47 UTC, marktwtn commented on tests/impl.cpp
> +    ASSERT_RETURN((uint64_t) c == ((*_a >> ((i & 0x3) * 16)) & 0xFFFF));
I suggest you to have a variable `idx` which equals to `i&03`, then you can replace `idx` in the code to make it more readable.

2021-05-04 03:04 UTC, marktwtn requested changes

2021-05-04 03:04 UTC, marktwtn commented on tests/impl.cpp
> +    ASSERT_RETURN(c == _a[i&0x7]);
Ditto.
And you can keep the original code writing format like `ASSERT_RETURN(c == *(_a + idx));`.

2021-05-04 03:09 UTC, marktwtn requested changes
Fix the coding style.

2021-05-05 05:55 UTC, marktwtn approved these changes

2021-05-05 06:05 UTC, jserv requested changes
I expect the change against the subject, which can be
> Improve the test coverage of _mm_extract_* intrinsics

2021-05-05 07:11 UTC, merged