fix: Fix implicit conversion warning
DLTcollab/sse2neon pull request #468
Opened 2021-07-25 15:45 UTC by HowJMay

Fix the following warning which is shown on Apple M1
```
warning: implicit conversion from 'int' to 'int8_t' (aka 'signed char')
    changes value from 135 to -121 [-Wconstant-conversion]
        vand_s8(vreinterpret_s8_m64(b), vdup_n_s8((0x1 << 7 | 0x07)));
                                        ~~~~~~~~~  ~~~~~~~~~^~~~~~
```

2021-07-25 19:05 UTC, jserv commented
Is the message identical when you build SSE2NEON with clang/linux?

2021-07-26 02:42 UTC, HowJMay commented
@jserv Based on the CI results which were run on ubuntu, the same error doesn't exist. However, there are more warnings that needs to handle. Should I open another PR for it or solve them in this PR?

2021-07-26 04:07 UTC, jserv commented
> @jserv Based on the CI results which were run on ubuntu, the same error doesn't exist. However, there are more warnings that need to be handled. Should I open another PR for it or solve them in this PR?

You shall eliminate the potential warnings raised by known compilers. Let's work on this pull request.

2021-07-26 12:45 UTC, HowJMay commented
@jserv all warnings are fixed.

2021-07-27 03:26 UTC, marktwtn requested changes

2021-07-27 03:26 UTC, marktwtn commented on tests/impl.cpp
> +        if (INT16_MAX <= (int) _a[i] && (int) _a[i] <= INT32_MAX) {
I prefer to cast the `INT16_MAX` to `float` since casting with `int` would have data loss.

2021-07-27 03:26 UTC, marktwtn commented on tests/impl.cpp
> +        if (INT8_MAX <= (int) _a[i] && (int) _a[i] <= INT32_MAX) {
Ditto.

2021-07-29 09:34 UTC, marktwtn approved these changes

2021-07-29 15:39 UTC, jserv commented
Don't use Markdown-specific syntax in git commit messages. Instead, always use plain text. Append `Close #471` at the end of the git commit message.

2021-07-31 17:18 UTC, merged