refactor: Update aeskeygenassist_si128 to optimized ver
DLTcollab/sse2neon pull request #573
Opened 2022-12-27 17:37 UTC by howjmay

2022-12-27 17:49 UTC, jserv requested changes
Refine the subject of this pull request and git commit message. You shall emphasize the benefit with the proposed changes.

2022-12-27 17:49 UTC, jserv commented on sse2neon.h
> +            w(0xc5), w(0x30), w(0x01), w(0x67), w(0x2b), w(0xfe), w(0xd7), \
Indent properly.

2022-12-28 03:39 UTC, jserv commented on sse2neon.h
> +#define SSE2NEON_AES_SBOX(w)                                               \
Can you move the definition out of function body?

2022-12-28 03:40 UTC, jserv commented on sse2neon.h
> +#define SSE2NEON_AES_SBOX(w)                                               \
Isn't `SSE2NEON_AES_SBOX` existing somewhere in the header already?

2022-12-28 07:50 UTC, howjmay commented
I found the previous implementation actually have used intrinsics. I will check the performance of my current implementation first, then reopen this PR.

2022-12-28 14:17 UTC, merged