fix: Fix MSVC warnings
DLTcollab/sse2neon pull request #604
Opened 2023-07-31 09:03 UTC by howjmay

2023-10-05 09:28 UTC, jserv requested changes
Rebase the latest master branch.

2023-11-05 17:20 UTC, jserv commented on sse2neon.h
> +    // muliplying 'x' by 2 in GF(2^8)
Don't change this.

2023-11-05 17:21 UTC, jserv commented on sse2neon.h
> +    // muliplying 'x' by 3 in GF(2^8)
Ditto. Minimize the necessary changes.

2023-11-05 18:24 UTC, howjmay commented
I think the rest warnings should be false positive

2023-11-05 18:25 UTC, merged