test: Run CI with optimization levels
DLTcollab/sse2neon pull request #638
Opened 2024-06-25 07:04 UTC by howjmay

2024-06-28 14:14 UTC, howjmay commented
`_mm_dp_pd` and `_mm_dp_ps` still have errors

2024-07-02 21:24 UTC, aqrit commented
Type punning via union is illegal in C++.
 C++20 added `std::bit_cast`.
Without `bit_cast` one could use `memcpy` for this, however that is still somewhat undefined?

Type punning via union is "okay" in C. Though it makes some assumptions about the floating point format and underlying integer types.

2024-07-03 12:31 UTC, howjmay commented
@aqrit 
Do you think I should change to the `memcpy` instead of using union?

2024-07-03 22:28 UTC, aqrit commented
AFAIK, `memcpy` is the only "safe" way to do this in C++ before C++20. 

```
#ifdef __cplusplus
# if __cplusplus >= 202002L
    // use bitcast
# else
    // use memcpy
# endif
#else // file is being compiled as "C"
    // use union
#endif
```

2024-07-09 08:31 UTC, howjmay commented
@aqrit how do you think about the new refactoring? I am using memcpy to recast variables now

2024-07-09 11:32 UTC, howjmay commented
@jserv If this implementation is ok, I will remove the optimization option and squash the commits

2024-07-09 12:09 UTC, jserv commented
> I still need some time to investigate the cause that makes `_mm_dp_pd` and `_mm_dp_ps` failed.

The above seems to be working. Is my understanding correct?

2024-07-09 13:31 UTC, howjmay commented
@jserv Yes. Here I have fixed `_mm_dp_pd` and `_mm_dp_ps`. The whole test cases were optimized in a wrong way, so we need to disable optimization for these two test cases

2024-07-09 14:23 UTC, jserv commented
> If this PR is ok, I will remove the optimization option and turn this PR into ready for review

Except for the `recast_f64` and `recast_i64` functions (the naming should be amended for consistency), I think the proposed changes are fine."

2024-07-10 16:53 UTC, howjmay commented
> > If this PR is ok, I will remove the optimization option and turn this PR into ready for review
> 
> Except for the `recast_f64` and `recast_i64` functions (the naming should be amended for consistency), I think the proposed changes are fine."

How about rename them as `sse2neon_recast_f64` and `sse2neon_recast_i64`?

2024-07-15 09:06 UTC, jserv commented
> How about renaming them as `sse2neon_recast_u64_f64` and `sse2neon_recast_f64_s64`?

It sounds pretty well.

2024-07-18 07:10 UTC, jserv requested changes
Since this is not a trivial change, the git commit messages should be amended to be more informative. You might consider to split the proposed changes into several commits.

2024-07-18 09:00 UTC, howjmay commented
@jserv I have added the commit message. 
However, when it comes to splitting this PR into several small commits, I think I can only separate it into a commit that introducing `OPTNONE` for some tests/intrinsics and another one handling the strict-aliasing errors. 
How do you think about it?

2024-07-18 09:38 UTC, jserv commented
Is it time to close #635 and #639 ? If so, refine the git commit messages accordingly.

2024-07-18 12:56 UTC, howjmay commented
I think it is ok now

2024-07-18 13:17 UTC, merged