fix test_mm_dp_pd test
DLTcollab/sse2neon pull request #643
Opened 2024-07-18 19:15 UTC by alexorlov124

When I ran make check with -O2 passed to ARCH_CFLAGS, the test_mm_dp_pd failed. After debugging, I discovered that a buffer initialized with floats was being cast to a buffer of doubles. The root cause of the test failure was that the exact match of the dot product obtained with intrinsics and calculated with C++ doubles showed differences. This occurred because the numbers were too large, and the dot product had rounding errors.

2024-07-18 19:44 UTC, howjmay commented
I think you use the different version of clang-format. It should be `clang-format-12`. But you can refer CI directly to format the code

2024-07-18 20:27 UTC, alexorlov124 commented
> I think you use the different version of clang-format. It should be `clang-format-12`. But you can refer CI directly to format the code

Thank you, I installed clang-formatter 12 and now format is fixed

2024-07-20 04:48 UTC, howjmay commented
Btw may I ask which compiler and platform you used to trigger the error?

2024-07-20 05:28 UTC, alexorlov124 commented
> Btw may I ask which compiler and platform you used to trigger the error?

I used gcc 10.2 and 11.4, Graviron3 and Amazon Linux 2023

2024-07-20 11:03 UTC, howjmay commented
Sorry it seems not to pass the CI. May you help me to enable `-O2` in the CI and check it ?

https://github.com/howjmay/sse2neon/actions/runs/10019289097

2024-07-20 13:46 UTC, alexorlov124 commented
> Sorry it seems not to pass the CI. May you help me to enable `-O2` in the CI and check it ?
> 
> https://github.com/howjmay/sse2neon/actions/runs/10019289097

I updated .github\workflows\main.yml with -O2 flag not sure we should merge it in master but we can make sure tests are green

2024-07-20 13:47 UTC, alexorlov124 commented
Here my pull request with optimization enabled https://github.com/DLTcollab/sse2neon/pull/644

2024-07-20 15:46 UTC, jserv requested changes
Squash the git commits and refine the commit messages.
See https://cbea.ms/git-commit/

2024-07-20 17:24 UTC, howjmay commented
> Here my pull request with optimization enabled #644

Thank you for the test. However, it seems the test didn't pass. Not sure if I did something wrong. 

I think this PR should be ok to merge after squash. But I just feel strange. It seems this PR can't solve the error when O2 is given

2024-07-25 14:33 UTC, merged

2024-07-25 14:33 UTC, jserv commented
Thank @alexorlov124 for contributing!

2024-07-25 14:43 UTC, howjmay commented
I will investigate what cause O2 fail in #642

2024-07-25 17:06 UTC, alexorlov124 commented
Welcome,
I could participate in investigating other test fails, Right now I need to
finish a project in my work.

Thank you!

чт, 25 июл. 2024 г. в 16:34, Jim Huang ***@***.***>:

> Thank @alexorlov124 <https://github.com/alexorlov124> for contributing!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DLTcollab/sse2neon/pull/643#issuecomment-2250483325>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK3RKY4UX5WMVI2MIVWOTO3ZOEEGVAVCNFSM6AAAAABLDIZ6YSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENJQGQ4DGMZSGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>